import { Navbar } from "@/components/ui/navbar";
import { Footer } from "@/components/ui/footer";
import { AlertTriangle } from "lucide-react";

export default function LegalPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1">
        {/* Header */}
        <section className="bg-card border-b border-border py-16">
          <div className="container">
            <div className="max-w-2xl mx-auto text-center">
              <h1 className="text-4xl font-bold text-foreground">
                Legal & Disclaimer
              </h1>
              <p className="mt-4 text-lg text-muted-foreground">
                Important information about how GreenTrack works and its limitations.
              </p>
            </div>
          </div>
        </section>

        {/* Content */}
        <section className="py-16 bg-background">
          <div className="container">
            <div className="max-w-3xl mx-auto">
              {/* Important Notice */}
              <div className="bg-accent/50 border border-accent-foreground/20 rounded-lg p-6 mb-12">
                <div className="flex items-start gap-4">
                  <AlertTriangle className="h-6 w-6 text-accent-foreground flex-shrink-0 mt-1" />
                  <div>
                    <h2 className="text-lg font-semibold text-foreground mb-2">
                      Important Notice
                    </h2>
                    <p className="text-muted-foreground">
                      GreenTrack is an <strong>internal ESG tracking and readiness tool</strong>. 
                      It is not a certification body, audit firm, or regulatory authority. 
                      The scores, reports, and summaries generated by this platform are for 
                      internal assessment and planning purposes only.
                    </p>
                  </div>
                </div>
              </div>

              {/* Sections */}
              <div className="space-y-12">
                <div>
                  <h2 className="text-2xl font-bold text-foreground mb-4">
                    What GreenTrack Is
                  </h2>
                  <ul className="space-y-3 text-muted-foreground">
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      A self-assessment tool to help businesses understand their current ESG standing
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      A goal-setting and tracking platform for sustainability initiatives
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      A documentation and evidence storage system for ESG-related materials
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      A report generation tool for internal and stakeholder communication
                    </li>
                  </ul>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-foreground mb-4">
                    What GreenTrack Is NOT
                  </h2>
                  <ul className="space-y-3 text-muted-foreground">
                    <li className="flex items-start gap-2">
                      <span className="text-destructive font-bold">✕</span>
                      Not a certification or accreditation body
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-destructive font-bold">✕</span>
                      Not a regulatory compliance verification service
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-destructive font-bold">✕</span>
                      Not an audit or assurance provider
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-destructive font-bold">✕</span>
                      Not a substitute for professional legal, environmental, or sustainability advice
                    </li>
                  </ul>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-foreground mb-4">
                    Carbon Emissions Disclaimer
                  </h2>
                  <p className="text-muted-foreground mb-4">
                    The carbon emission calculations provided by GreenTrack are <strong>estimates 
                    for internal tracking purposes only</strong>. These calculations:
                  </p>
                  <ul className="space-y-3 text-muted-foreground">
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      Use average emission factors and may not reflect your specific situation
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      Are not verified or audited by third parties
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      Should not be used for carbon offset claims or regulatory reporting
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      Are intended to help you understand trends, not make official declarations
                    </li>
                  </ul>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-foreground mb-4">
                    Data & Privacy
                  </h2>
                  <p className="text-muted-foreground mb-4">
                    We take your data security seriously:
                  </p>
                  <ul className="space-y-3 text-muted-foreground">
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      All data is encrypted in transit and at rest
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      Your ESG data is private and only visible to your workspace members
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      Shareable links only show what you explicitly choose to share
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary font-bold">•</span>
                      We do not sell or share your data with third parties
                    </li>
                  </ul>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-foreground mb-4">
                    Limitation of Liability
                  </h2>
                  <p className="text-muted-foreground">
                    GreenTrack and its operators shall not be held liable for any business decisions 
                    made based on the scores, reports, or summaries generated by this platform. 
                    Users are advised to consult qualified professionals for regulatory compliance, 
                    legal matters, and official sustainability reporting.
                  </p>
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-foreground mb-4">
                    Contact Us
                  </h2>
                  <p className="text-muted-foreground">
                    For questions about this disclaimer or our services, please contact us at{" "}
                    <a href="mailto:legal@greentrack.in" className="text-primary hover:underline">
                      legal@greentrack.in
                    </a>
                  </p>
                </div>
              </div>

              {/* Last Updated */}
              <p className="text-sm text-muted-foreground mt-12 pt-8 border-t border-border">
                Last updated: January 2025
              </p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
